clas/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('lista/', views.cla_list, name="cla_list"),
    path('cla/<int:pk>', views.cla_detail, name="cla_detail"),
    path('cla_novo', views.cla_create, name="cla_create"),
    path('', views.home, name="home")
]

locais/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('lista/', views.local_list, name='local_list'),
    path("novo/", views.local_novo, name="local_novo"),
    path('detalhes/<int:pk>', views.local_detail, name='local_detail')
]

wodTimeline/urls.py
# /wodTimeline/urls.py

"""
URL configuration for wodTimeline project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls', namespace='livros')),
    path('disciplinas/', include('disciplinas.urls')),
    path('clas/', include('clas.urls')),
    path('personagens/', include('personagens.urls')),
    path('locais/', include('locais.urls')),
    path('eventos/', include('eventos.urls', namespace='eventos')),
    path('', views.home, name='home'),
]

locais/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
# from datetime import date
from livros.models import Livro


# Create your models here.
class Local(models.Model):

    DIMENSAO_CHOICE = (
        ('1', 'Terreno'         ),
        ('2', 'Umbra rasa'      ),
        ('3', 'Umbra media'     ),
        ('4', 'Umbra profunda'  ),
        ('5', 'Sonhar proximo'  ),
        ('6', 'Sonha distante'  ),
        ('7', 'Sonhar profundo' ),
        ('8', 'Teia digital'    ),
    )

    nome = models.CharField(_("Nome"), max_length=100)
    regiao = models.CharField(_("Região"), max_length=200, null=True, blank=True)
    dimensao = models.CharField(_("Dimensão"), max_length=3, choices=DIMENSAO_CHOICE, null=True, blank=True)
    era = models.CharField(_("Era"), max_length=100, null=True, blank=True)
    livro = models.ForeignKey(Livro, verbose_name=_("Livro"), on_delete=models.CASCADE)
    criado_em = models.DateField(_("Criado em"), auto_now=False, auto_now_add=True)
    autualizado_em = models.DateField(_("Atualizado em"), auto_now=True, auto_now_add=False)
    
    class Meta:
        verbose_name = _("Local")
        verbose_name_plural = _("Locais")

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse("Local_detail", kwargs={"pk": self.pk})

locais/forms.py
from django import forms 
from .models import Local

# Formalario
class LocalForm(forms.ModelForm):
    
    class Meta:
        model = Local
        fields = (
            'nome', 'regiao', 'dimensao', 'era', 'livro'
        )

locais/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Local
from .forms import LocalForm

# Cria suas views aqui.
def home(request):  # Define a view chamada "home"
    return render(request, 'locais/home.html')  # Renderiza o template 'home.html' na pasta 'locais'

# View para listagem de locais
def local_list(request):  # Define a view chamada "local_list" para listar os locais
    local = Local.objects.all()  # Atribui à variável 'local' todos os itens da tabela 'Local'
    
    context = {  # Cria um dicionário de contexto para passar ao template
        'local': local,  # Passa a variável 'local' (todos os itens da tabela 'Local') para o template
        'title': 'Lista de locais'  # Passa uma string 'Lista de locais' como título da página
    }
    return render(request, 'locais/locais_list.html', context)  # Renderiza o template 'locais_list.html' na pasta 'locais' com as variáveis do contexto

def local_novo(request):  # Define a view para adicionar um novo local
    if request.method == 'POST':  # Verifica se o método da requisição é POST
        form = LocalForm(request.POST)  # Instancia o formulário com os dados enviados
        if form.is_valid():  # Verifica se o formulário é válido
            novo_local = form.save()  # Salva os dados do formulário no banco de dados
            if request.POST.get('action') == 'save_and_add_new':
                return redirect('local_novo')
            return redirect('local_detail', pk=novo_local.pk)  # Redireciona para a detalhes da nova entrada
    else:  # Se o método da requisição não for POST
        form = LocalForm()  # Instancia um formulário vazio
    
    context = {  # Cria o dicionário de contexto para passar ao template
        'form': form,  # Passa o formulário para o template
        'title': 'Adicionar novo Local'  # Passa o título da página para o template
    }
    return render(request, 'locais/locais_form.html', context)  # Renderiza o template com o contexto


def local_detail(request, pk):
    local = get_object_or_404(Local,pk=pk)
    context = {
        'local': local,
        'title': f'Detalhes do Local: {local.nome} - {local.livro}'
    }
    return render(request, 'locais/locais_detail.html', context)

locais/templates/locais/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Locais Home</title>
</head>
<body>
    Locais home
</body>
</html>

locais/templates/locais/locais_detail.html
<!-- edicoes/templates/edicoes/edicao_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>Nome     : {{ local.nome     }}</p>
    <p>regiao   : {{ local.regiao   }}</p>
    <p>dimensao : {{ local.get_dimensao_display }}</p>
    <p>era      : {{ local.era      }}</p>
    <p>livro    : {{ local.livro    }}</p>

    <br>
    <a href="{% url 'local_list' %}">Voltar à lista de Locais</a>
</body>
</html>

locais/templates/locais/locais_form.html
<!-- locais/templates/locais/locais_form.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
        <button type="submit" name="action" value="save_and_add_new">Salvar e adicionar nova entrada</button>
    </form>
    <br>
    <a href="{% url 'local_list' %}">Voltar à lista de locais</a>
</body>
</html>

locais/templates/locais/locais_list.html
<!-- edicoes/templates/edicoes/edicao_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <ul>
        {% for local in local %}
            <li>
                <a href="{% url 'local_detail' local.pk %}">{{ local.nome }} - {{ local.livro }}</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'local_novo' %}">Adicionar Novo Local</a>
</body>
</html>