clas/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('lista/', views.cla_list, name="cla_list"),
    path('cla/<int:pk>', views.cla_detail, name="cla_detail"),
    path('cla_novo', views.cla_create, name="cla_create"),
    path('', views.home, name="home")
]

livros/urls.py
# livros/urls.py

from django.urls import path
from . import views

app_name = 'livros'

urlpatterns = [
    path('', views.home, name="home"),
    path('lista/', views.livro_list, name='livro_list'),
    path('livro/<int:pk>/', views.livro_detail, name='livro_detail'),
    path('livro_novo/', views.livro_create, name='livro_create'),
    path('edicao/', views.edicao_list, name='edicao_list'),
    path('edicao/<int:pk>/', views.edicao_detail, name='edicao_detail'),
    path('edicao_nova/', views.edicao_create, name='edicao_create'),
]

wodTimeline/urls.py
# /wodTimeline/urls.py

"""
URL configuration for wodTimeline project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls', namespace='livros')),
    path('disciplinas/', include('disciplinas.urls')),
    path('clas/', include('clas.urls')),
    path('personagens/', include('personagens.urls')),
    path('locais/', include('locais.urls')),
    path('eventos/', include('eventos.urls', namespace='eventos')),
    path('', views.home, name='home'),
]

livros/models.py
# models/models.py

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


# Modelo para representar uma edição
class Edicao(models.Model):
    # Nome da edição
    nome = models.CharField(_("Nome"), max_length=100)
    # Timestamp de criação
    criado_em = models.DateField(_("Criado em"), auto_now_add=True)
    # Timestamp de atualização
    atualizado_em = models.DateField(_("Atualizado em"), auto_now=True)

    class Meta:
        # Nome singular e plural para o modelo
        verbose_name = _("edição")
        verbose_name_plural = _("edições")

    def __str__(self):
        # Representação em string do objeto Edicao
        return self.nome

    def get_absolute_url(self):
        # URL para acessar detalhes de uma edição específica
        return reverse("Edicao_detail", kwargs={"pk": self.pk})


# Modelo para representar um livro
class Livro(models.Model):
    # Nome do livro
    nome = models.CharField(_("Nome"), max_length=100, blank=False, null=False)
    # Relacionamento com a edição
    edicao = models.ForeignKey(Edicao, verbose_name=_("Edição"), on_delete=models.CASCADE)
    # Nome da editora
    editora = models.CharField(_("Editora"), max_length=100)
    # Revisão do livro (opcional)
    revisao = models.CharField(_("Revisão"), max_length=50, blank=True, null=True)
    # ISBN do livro (opcional)
    isbn = models.CharField(_("ISBN"), max_length=13, blank=True, null=True)
    # Timestamp de criação
    criado_em = models.DateField(_("Criado em"), auto_now_add=True)
    # Timestamp de atualização
    atualizado_em = models.DateField(_("Atualizado em"), auto_now=True)

    class Meta:
        # Nome singular e plural para o modelo
        verbose_name = _("livro")
        verbose_name_plural = _("livros")

    def __str__(self):
        # Representação em string do objeto Livro
        return f"{self.nome} - {self.edicao.nome}"

    def get_absolute_url(self):
        # URL para acessar detalhes de um livro específico
        return reverse("Livro_detail", kwargs={"pk": self.pk})

livros/forms.py
# livros/forms.py

from django import forms
from .models import Livro, Edicao

class LivroForm(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['nome', 'edicao', 'editora', 'revisao', 'isbn']

class EdicaoForm(forms.ModelForm):
    class Meta:
        model = Edicao
        fields = ['nome']

livros/views.py
# livros/views.py

from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .models import Livro, Edicao
from .forms import LivroForm, EdicaoForm


# home
def home(request):
    return render(request, 'livros/home.html')


# View to list all books
def livro_list(request):
    livros = Livro.objects.all()
    context = {
        'livros': livros,
        'title': 'Lista de Livros'
    }
    return render(request, 'livros/livro_list.html', context)

# View to see the details of a single book
def livro_detail(request, pk):
    livro = get_object_or_404(Livro, pk=pk)
    context = {
        'livro': livro,
        'title': f'Detalhes do Livro: {livro.nome}'
    }
    return render(request, 'livros/livro_detail.html', context)

# View to add a new book
def livro_create(request):
    if request.method == 'POST':
        form = LivroForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('livro_list')
    else:
        form = LivroForm()
    context = {
        'form': form,
        'title': 'Adicionar Novo Livro'
    }
    return render(request, 'livros/livro_form.html', context)

#### Views for `Edicao`

# View to list all editions
def edicao_list(request):
    edicoes = Edicao.objects.all()
    context = {
        'edicoes': edicoes,
        'title': 'Lista de Edições'
    }
    return render(request, 'livros/edicao_list.html', context)

# View to see the details of a single edition
def edicao_detail(request, pk):
    edicao = get_object_or_404(Edicao, pk=pk)
    context = {
        'edicao': edicao,
        'title': f'Detalhes da Edição: {edicao.nome}'
    }
    return render(request, 'livros/edicao_detail.html', context)

# View to add a new edition
def edicao_create(request):
    if request.method == 'POST':
        form = EdicaoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('edicao_list')
    else:
        form = EdicaoForm()
    context = {
        'form': form,
        'title': 'Adicionar Nova Edição'
    }
    return render(request, 'livros/edicao_form.html', context)

livros/templates/livros/edicao_detail.html
<!-- edicoes/templates/edicoes/edicao_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>Nome: {{ edicao.nome }}</p>
    <a href="{% url 'livros:edicao_list' %}">Voltar à lista de edições</a>
</body>
</html>

livros/templates/livros/edicao_form.html
<!-- edicoes/templates/edicoes/edicao_form.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'livros:edicao_list' %}">Voltar à lista de edições</a>
    <br>
    <a href="{% url 'livros:livro_create' %}">Voltar para adicionar Novo Livro</a>
</body>
</html>

livros/templates/livros/edicao_list.html
<!-- edicoes/templates/edicoes/edicao_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <ul>
        {% for edicao in edicoes %}
            <li>
                <a href="{% url 'livros:edicao_detail' edicao.pk %}">{{ edicao.nome }}</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'livros:edicao_create' %}">Adicionar Nova Edição</a>
</body>
</html>

livros/templates/livros/home.html
<!DOCTYPE html>
<html>
<head>
    <title>home</title>
</head>
<body>
    <h1>home</h1>
    <ul>
        <p> home </p>
        <a class="navbar-brand" href="{% url 'home' %}"><img src= '#'  width="20px" alt="">&nbspwodTimeline</a>
    </ul>
    
</body>
</html>

livros/templates/livros/livro_detail.html
<!-- livros/templates/livros/livro_detail.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>Nome: {{ livro.nome }}</p>
    <p>Edição: {{ livro.edicao.nome }}</p>
    <p>Editora: {{ livro.editora }}</p>
    <p>Revisão: {{ livro.revisao }}</p>
    <p>ISBN: {{ livro.isbn }}</p>
    <a href="{% url 'livros:livro_list' %}">Voltar à lista de livros</a>
</body>
</html>

livros/templates/livros/livro_form.html
<!-- livros/templates/livros/livro_form.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'livros:edicao_create' %}">Adicionar Nova Edição</a>
    <br>
    <a href="{% url 'livros:livro_list' %}">Voltar à lista de livros</a>
</body>
</html>

livros/templates/livros/livro_list.html
<!-- livros/templates/livros/livro_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <ul>
        {% for livro in livros %}
            <li>
                <a href="{% url 'livros:livro_detail' livro.pk %}">{{ livro.nome }} - {{ livro.edicao.nome }}</a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'livros:livro_create' %}">Adicionar Novo Livro</a>
</body>
</html>